backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/media
public_folder: /media

collections:
  - name: "widgets"
    label: "Widgets"
    files:
      - file: "src/widgets/next-meeting.md"
        label: "Next Meeting"
        name: "next-meeting"
        fields:
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Location", name: "string", widget: "string" }
          - { label: "Agenda", name: "agenda", widget: "file" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/data/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden" }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Signature, name: signature, widget: string }
          - { label: Link, name: link, widget: object, fields: [{ label: Text, name: text, widget: string }, { label: Path, name: path, widget: string }] }
