backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/media
public_folder: /media

collections:
  - name: "categories"
    label: "Categories"
    folder: "src/app/categories"
    create: true
    format: "json"
    fields:
      - { label: Title, name: title, widget: string }
  - name: "posts"
    label: "Posts"
    folder: "src/app/pages/posts"
    create: true
    slug: "{{slug}}"
    summary: "{{title}} {{fields.featured}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "project-page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredimage", widget: object, fields: [{ label: Image, name: image, widget: image }, { label: Alt, name: alt, widget: string }] }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Category", name: category, widget: "relation", collection: "categories", search_fields: ["title"], value_field: "title", display_fields: ["title"] }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/app/pages/index/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - { label: "Template Key", name: templateKey, widget: "hidden", default: "index" }
          - { label: "Type", name: type, widget: "hidden", default: "page" }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Main Image", name: image, widget: image }
      - file: "src/app/pages/about-us/index.md"
        label: "About Us"
        name: "about-us"
        fields:
          - { label: "Template Key", name: templateKey, widget: "hidden", default: "about-us" }
          - { label: "Type", name: type, widget: "hidden", default: "page" }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Main Image", name: image, widget: image }
          - { label: "Body", name: body, widget: markdown }
      - file: "src/app/pages/contact-us/index.md"
        label: "Contact Us"
        name: "contact-us"
        fields:
          - { label: "Template Key", name: templateKey, widget: "hidden", default: "contact-us" }
          - { label: "Type", name: type, widget: "hidden", default: "page" }
          - { label: "Title", name: title, widget: "string" }
          - { label: "Main Image", name: image, widget: image }
          - { label: "Body", name: body, widget: markdown }
